export default {
  SCREEN_MAIN: "Home ",
  SCREEN_HOME: "Home",
  SCREEN_MY_ASSETS: "My Assets",
  SCREEN_MY_RENTALS: "My Rentals",
  SCREEN_AUTHENTICATE: "Authenticate",
  SCREEN_ADD_ASSET: "Add Asset",
  SCREEN_BILLING: "Billing Info",
  SCREEN_FIND_ASSET: "FindAsset",
  SCREEN_PAY_BOOKINGS: "Payment",
  SCREEN_AVILABLE_ASSETS: "Available Assets",
  SCREEN_ASSET_INFO: "Asset Information",
  SCREEN_MAP: "Map",
  SCREN_ASSETS_MAP: "Assets Map",
  SCREEN_ASSET_EDIT: "Edit Asset",
  NAVIGATOR_MY_ASSETS_SCREEN: "Manage Assets",
  NAVIGATOR_AVILABLE_ASSETS_SCREEN: "Find Assets",
  NAVIGATOR_DRAWER: "Drawer",
};
